adiciona rota de download e modifica o upload do certificado
Guardians-DSC/API-HoCo pull request #10
Opened 2022-11-09 22:26 UTC by dnlgomesl

Antes de fazer o PR por favor preencha o seguinte formulário:

### Meu pull request

- [ x ] Adiciona uma nova funcionalidade;
- [ ] Conseta um bug;
- [ ] Adiciona uma documentação;
- [ ] Adiciona alguma otimização ao sistema;
- [ ] Adiciona alguma configuração.

### O que o pull request faz?

Possibilita o download do certificado. Foi criado a rota de download do certificado e modificado a rota de upload para que que a rota de download possa funcionar.

### Como faço para testar essa PR?

Primeiramente enviei um certificado em pdf como requisição, seguindo o exemplo a seguir:

![image](https://user-images.githubusercontent.com/50140741/200954949-3cc06836-6e5e-4568-b08c-3d1df29aed17.png)

Após isso basta ir no browser e colar sua url para dowload, seguindo o exemplo a seguir:

**_url_exemplo/activity/download/<file_name>_**

Seguindo o exemplo da imagem a url seria assim:

**_url_exemplo/activity/download/epol-certificate_**

2022-11-28 22:34 UTC, RodrigoEC commented
Amg, ta muito massa!! Mas tem duas coisinhas que acho que a gente poderia melhorar:

- Teria como tu fazer o download pelo `id` do arquivo ao invés do nome do arquivo? Isso seria melhor porque a gente evita problemas com arquivos que tem o mesmo nome.

- Tu pode implementar o download com: nome-do-arquivo.extensão? Porque agora só está fazendo o download com o nome do arquivo.

2022-11-29 19:12 UTC, RodrigoEC requested changes

2022-11-29 19:12 UTC, RodrigoEC commented on api_hoco/controllers/activity.py
> +        response.headers["Content-Disposition"] = "attachment; filename={}".format(file_name)
```suggestion
        response.headers["Content-Disposition"] = f"attachment; filename={file_name}"
```

2022-11-29 23:45 UTC, dnlgomesl commented on api_hoco/controllers/activity.py
> +        response.headers["Content-Disposition"] = "attachment; filename={}".format(file_name)
Não entendi muito bem esse segundo ponto. Analisando o banco ele não salva a extensão do arquivo, entretanto o download funciona pra arquivos diferentes, é mantido a extenção. Se é pdf o download é um pdf, se é imagem o download é imagem.

Segue o print do banco

![image](https://user-images.githubusercontent.com/50140741/204672934-010f4ee6-83bb-49e1-ad77-3c96d905d840.png)

Esses dois arquivos são de extensões diferentes.

2022-11-29 23:48 UTC, dnlgomesl commented
Correções feitas

2022-12-01 12:58 UTC, RodrigoEC commented on api_hoco/controllers/activity.py
> +        response.headers["Content-Disposition"] = "attachment; filename={}".format(file_name)
Eita, que estranho, o pior é que se a gente não coloca extensão fica estranho, mas deixa sem mesmo

2022-12-07 19:12 UTC, merged